# Generated by Django 2.1.7 on 2019-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelwithdeprecatedfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithdeprecatedfield',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
